# CMake generated Testfile for 
# Source directory: /mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests
# Build directory: /mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pubsub "pubsub" "0")
set_tests_properties(pubsub PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;3;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_with_compression "pubsub" "1")
set_tests_properties(pubsub_with_compression PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;4;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_slowsub_conflate_0 "pubsub_slowsub_conflate" "0")
set_tests_properties(pubsub_slowsub_conflate_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;8;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_slowsub_conflate_1 "pubsub_slowsub_conflate" "1")
set_tests_properties(pubsub_slowsub_conflate_1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;9;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_slowsub_conflate_zmq_0 "pubsub_slowsub_conflate_zmq" "0")
set_tests_properties(pubsub_slowsub_conflate_zmq_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;13;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_slowsub_conflate_zmq_1 "pubsub_slowsub_conflate_zmq" "1")
set_tests_properties(pubsub_slowsub_conflate_zmq_1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;14;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub2 "pubsub2")
set_tests_properties(pubsub2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;26;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_unmanaged "pubsub_unmanaged")
set_tests_properties(pubsub_unmanaged PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;30;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_raw "pubsub_raw")
set_tests_properties(pubsub_raw PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;34;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_many "pubsub_many")
set_tests_properties(pubsub_many PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;38;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(pubsub_poll "pubsub_poll")
set_tests_properties(pubsub_poll PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;42;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(clisrv "clisrv")
set_tests_properties(clisrv PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;46;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(clisrv2 "clisrv2")
set_tests_properties(clisrv2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;50;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(clisrv_raw "clisrv_raw")
set_tests_properties(clisrv_raw PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;54;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(clisrv_badname "clisrv_badname")
set_tests_properties(clisrv_badname PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;58;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(clisrv_retry "clisrv_retry")
set_tests_properties(clisrv_retry PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;62;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(time_sync_offset_recover "time_sync_offset_recover")
set_tests_properties(time_sync_offset_recover PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;66;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(time_sync_clock_tracking_1 "time_sync_clock_tracking" "0.5" "0.6" "1")
set_tests_properties(time_sync_clock_tracking_1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;70;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(time_sync_clock_tracking_2 "time_sync_clock_tracking" "0.5" "1.5" "1")
set_tests_properties(time_sync_clock_tracking_2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;71;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(time_sync_clock_tracking_3 "time_sync_clock_tracking" "0.5" "1.66" "0")
set_tests_properties(time_sync_clock_tracking_3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;72;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(effective_spin_rate "effective_spin_rate")
set_tests_properties(effective_spin_rate PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;76;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(compress-zlib "compress" "zlib")
set_tests_properties(compress-zlib PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;80;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(compress-lz4 "compress" "lz4")
set_tests_properties(compress-lz4 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;81;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(announce_timeout "announce_timeout" "1000" "1")
set_tests_properties(announce_timeout PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;85;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(announce_notimeout "announce_timeout" "--timeout=-1" "-e0")
set_tests_properties(announce_notimeout PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;86;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(two_nodes_one_thread "two_nodes_one_thread")
set_tests_properties(two_nodes_one_thread PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;90;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(check_resolver_status_when_not_running "check_resolver_status" "0")
set_tests_properties(check_resolver_status_when_not_running PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;94;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(check_resolver_status_when_running "check_resolver_status" "1")
set_tests_properties(check_resolver_status_when_running PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;95;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(protocol "protocol")
set_tests_properties(protocol PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;99;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(json "json")
set_tests_properties(json PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;103;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(args "args_parse" "-a" "1" "-a" "2" "-a" "3" "-b" "0.5" "-c" "281474976710656" "-n" "4" "w" "x" "y" "z")
set_tests_properties(args PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;107;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(multi_resolver "multi_resolver")
set_tests_properties(multi_resolver PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;111;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(many_nodes "many_nodes")
set_tests_properties(many_nodes PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;115;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
add_test(resolver_shutdown "resolver_shutdown")
set_tests_properties(resolver_shutdown PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;119;add_test;/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/bluezero/tests/CMakeLists.txt;0;")
