close all
clear all
clc
%constants
D=0.2286;%9in
p = 1.225; %kg/m^3 density of air 1.225
Va = 8.9408; %20mph in m/s
n = 0.01:0.05:200; %Rotations per second
J = Va./(n*D);% advance ratio
Ct0 = 0.055836;%coefficents to make polynomial regression of thrust coefficent based of data from elkaim cheatsheet
Ct1 = -0.071498;
Ct2 = -0.081876;
Cq0 = 1.8379244897959134e-003;
Cq1 = 3.3921908763506112e-003;
Cq2 = -1.3052220888355488e-002;
J2 = Va/(7300*D);
%Ct0 = 0.09357;%coefficents used for 163's 20 inch propeller
%Ct1 = -0.06044;
%Ct2 = -0.1079;
Ct=Ct0 + (Ct1.*J) + (Ct2.*(J.^2));%Thrust Coefficent
Cq=Cq0 + (Cq1.*J2) + (Cq2.*(J2.^2))%torque Coefficent
%equation
F=p.*(n.^2).*(D^4).*Ct; %prop force equation
figure ;
plot(n*60,F);
xlabel('RPM');
ylabel('Thrust (N)');
title('Thrust Generated by 9" prop');